- name: Copy Pre-Post scripts validation Windows
  hosts: localhost
  gather_facts: no

  vars:
    vcenter_hostname: "10.253.104.155"
    vcenter_username: ".com"
    vcenter_password: "Gl"
    datacenter_name: "COLTC"

    vm_guest_user: "cwb"
    vm_guest_password: "C"

    local_zip: "../Script.zip"
    remote_zip: "C:\\Temp\\Script.zip"
    remote_folder: "C:\\Temp\\Script"
    ps_script: "C:\\Temp\\Script\\Win-Pre.ps1"
    vms:
        - "PRUEBACOMMVAULT"

  tasks:
    - name: Generar script PowerCLI
      template:
        src: copy_zip_coforge.ps1.j2
        dest: /tmp/deploy_script.ps1

    - name: Ejecutar PowerCLI
      command: pwsh /tmp/deploy_script.ps1
